# Generated by Django 3.0.3 on 2020-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=None, max_length=64)),
                ('course_name', models.CharField(default=None, max_length=128)),
                ('course_duration', models.IntegerField(default=0)),
                ('initial_payment', models.IntegerField(default=0)),
                ('recurring_payment', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=0)),
            ],
        ),
    ]
