# Generated by Django 3.0.3 on 2020-02-18 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusRegistration',
            fields=[
                ('mobile_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=32)),
                ('first_name', models.CharField(default=None, max_length=62)),
                ('last_name', models.CharField(default=None, max_length=62)),
                ('is_registered_app', models.BooleanField(default=False, verbose_name='App Downloaded')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name="Today's Date")),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Student Username')),
                ('campus_id', models.CharField(choices=[], default=None, max_length=10)),
                ('coordinator_name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Registration Date')),
                ('course_id', models.CharField(choices=[('ID-1', 'Course 1'), ('ID-2', 'Course 2'), ('ID-3', 'Course 3'), ('ID-4', 'Course 4')], max_length=30)),
                ('batch_id', models.CharField(default=None, max_length=32)),
                ('course_activation_id', models.CharField(default=None, max_length=64)),
                ('student_id', models.ForeignKey(db_column='student_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='registered_course', to='campus_registration.CampusRegistration', verbose_name='Campus Student')),
            ],
        ),
    ]
