# Generated by Django 3.0.3 on 2020-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0003_auto_20200218_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusregistration',
            name='campus_id',
            field=models.CharField(choices=[('ambg', 'Arambagh')], default=None, max_length=10),
        ),
    ]
