# Generated by Django 3.0.3 on 2020-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0006_auto_20200225_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='admission_fees_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='fees_status',
            field=models.BooleanField(default=False, verbose_name='Fees Status (Tick if Paid)'),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='payment_mode',
            field=models.CharField(choices=[('CSH', 'CASH'), ('GPAY', 'GOOGLE PAY'), ('PayTM', 'PAYTM')], default=None, max_length=32, verbose_name='Modes of payment'),
        ),
    ]
