# Generated by Django 3.0.3 on 2020-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0007_auto_20200302_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='transaction_id',
            field=models.CharField(default=None, max_length=234, verbose_name='Enter the Transaction id (Cash memo number for Cash Mode)'),
        ),
    ]
