# Generated by Django 3.0.3 on 2020-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0009_campusregistration_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusregistration',
            name='enrollment_id',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
