# Generated by Django 3.0.3 on 2020-03-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0010_auto_20200302_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusregistration',
            name='enrollment_id',
        ),
    ]
