# Generated by Django 3.0.3 on 2020-03-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0012_campusregistration_enrollment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusregistration',
            name='enrollment_id',
        ),
    ]
