# Generated by Django 3.0.3 on 2020-03-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_registration', '0014_campusregistration_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcourse',
            name='course_id',
            field=models.CharField(choices=[('PRTET', 'Primary TET'), ('CGL', 'Combined Graduate Level')], max_length=30),
        ),
    ]
