# Generated by Django 3.0.3 on 2020-02-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(default=None, max_length=64)),
                ('campus_code', models.CharField(default=None, max_length=20)),
                ('coordinator_names', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus.Coordinator', verbose_name='Coordinators')),
            ],
        ),
    ]
