# Generated by Django 3.0.3 on 2020-02-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='coordinator_names',
        ),
    ]
