# Generated by Django 3.0.3 on 2020-02-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_campus_coordinator_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='campus.Campus'),
        ),
    ]
